{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.135.7627.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact_data\",\"dictionary\",\"_Measure\",\"Data Refresh\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3dc3f6e0-8c8b-b2f2-a1b1-01596daa65a3",
        "fromColumn": "Date",
        "fromTable": "Fact_data",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "d22d6785-fd3a-465e-babc-39644c467bbf",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57aec725-9763-42d9-a8f2-4185c27e9440",
            "sourceColumn": "Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "Amount, $",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9c7a8f9-efb0-4a3c-9a32-097da6d1f12d",
            "sourceColumn": "Amount, $",
            "summarizeBy": "sum"
          },
          {
            "name": "Expense subgroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1aa5fe3c-cb58-4ec8-9d9b-ef392f117a81",
            "sourceColumn": "Expense subgroup",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue / Expense Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f977746e-1c19-4a14-bd2c-18d13b823db0",
            "sourceColumn": "Revenue / Expense Group",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue or expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29f559f3-5c40-480d-9841-64890d32a8d3",
            "sourceColumn": "Revenue or expense",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06017209-4f89-4557-9abe-69972d73ec60",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Busine_Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4693df6-3d8c-401e-b2e6-4e69a7f977ec",
            "sourceColumn": "Busine_Line",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1daf1cf9-1592-4036-a67f-ebd06cc3fefd",
        "partitions": [
          {
            "name": "Fact_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\_Financial Dashboard\\Financial_Dashboard\\Financial Statement.xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"Year\", Int64.Type}, {\"Month - name\", type text}, {\"Month -sequence\", Int64.Type}, {\"Date\", type date}, {\"Business Line\", type text}, {\"Amount, $\", Int64.Type}, {\"Expense subgroup\", type text}, {\"Revenue / Expense Group\", type text}, {\"Revenue or expense\", type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"Amount, $\", \"Amount, $ - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Amount, $ - Copy\", \"Amount\"}}),",
                "    #\"Calculated Absolute Value\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Amount\", Number.Abs, Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Calculated Absolute Value\",{\"Year\", \"Month - name\", \"Month -sequence\"}),",
                "    #\"Inserted Replaced Text\" = Table.AddColumn(#\"Removed Columns\", \"Replaced Text\", each Text.Replace(Text.Proper([Business Line]), \"AndFood Supplements\", \" & Food_Sup\"), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Replaced Text\",{{\"Replaced Text\", \"Busine_Line\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dictionary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd8ba603-32fc-46d8-ae20-cf12b09986d2",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Year of revenue/expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb9cb4af-0f9e-42e8-b5c4-1a52f6db6591",
            "sourceColumn": "Year of revenue/expense",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8ef584b3-9c3f-48d1-89f3-8ebe473571cc",
        "partitions": [
          {
            "name": "dictionary",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\_Financial Dashboard\\Financial_Dashboard\\Financial Statement.xlsx\"), null, true),",
                "    dictionary_Sheet = Source{[Item=\"dictionary\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dictionary_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", type text}, {\"Year of revenue/expense\", type any}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "d203632c-0dc2-4666-b273-4e1fa003ce8b",
        "measures": [
          {
            "name": "Total",
            "expression": "SUM(Fact_data[Amount])",
            "formatString": "0",
            "lineageTag": "1563f451-113f-4391-a0ad-36ac073a1813"
          },
          {
            "name": "Total Revenue",
            "expression": "CALCULATE([Total], Fact_data[Revenue or expense]=\"Revenue\")",
            "formatString": "#,0",
            "lineageTag": "4e87492e-57b3-498b-98b2-d51af0519df0"
          },
          {
            "name": "Total Expense",
            "expression": "CALCULATE([Total], Fact_data[Revenue or expense]=\"expense\")",
            "formatString": "0",
            "lineageTag": "74bdb7e2-d9b4-46ef-b160-808f9c053eba"
          },
          {
            "name": "PM Revenue",
            "expression": "CALCULATE([Total Revenue], DATEADD('Date'[Date], -1,MONTH)) + 0",
            "formatString": "0",
            "lineageTag": "24c88aa0-0a6a-4062-bad5-055552b98017"
          },
          {
            "name": "MoM rev %",
            "expression": "DIVIDE([Total Revenue]-[PM Revenue], [PM Revenue], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0d8f567e-2622-4bba-b081-6e9319278484"
          },
          {
            "name": "Rev label BG Color",
            "expression": "IF([MoM rev %]>0, \"#A5D6A7\", \"#FFAB91\")",
            "lineageTag": "b0e20f07-144e-47f7-af5a-9440ac005287"
          },
          {
            "name": "PM Expense",
            "expression": "CALCULATE([Total Expense], DATEADD('Date'[Date], -1, MONTH))",
            "formatString": "0",
            "lineageTag": "f20ac1a3-b5bb-46d3-ace7-d8b2115802a4"
          },
          {
            "name": "MoM Exp %",
            "expression": "DIVIDE([Total Expense]-[PM Expense], [PM Expense], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "49a1785a-5779-4e81-b0d0-0d8a53602806"
          },
          {
            "name": "COGS",
            "expression": "CALCULATE([Total], Fact_data[Revenue / Expense Group]=\"COGS\")",
            "formatString": "#,0",
            "lineageTag": "cc3444f5-5134-42a1-80ac-efc5b2073544"
          },
          {
            "name": "Gross Profit",
            "expression": "[Total Revenue]- [COGS]",
            "formatString": "#,0",
            "lineageTag": "e881854f-f09e-4ac0-8b5b-07c2734f4c81"
          },
          {
            "name": "GP Margin %",
            "expression": "DIVIDE([Gross Profit], [Total Revenue], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a74bdcb1-7632-4fe4-82c6-711d940e25bb"
          },
          {
            "name": "MoM GP %",
            "expression": [
              "",
              "VAR PM_gp = CALCULATE([Gross Profit], DATEADD('Date'[Date], -1, MONTH))",
              "VAR reg_gp = [Gross Profit]",
              "VAR Diff = reg_gp- PM_gp",
              "VAR Result = DIVIDE(Diff, PM_gp, 0)",
              "RETURN",
              "    Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4199c7e2-c1ef-4030-ba95-d6b4dcff665a"
          },
          {
            "name": "Net Profit",
            "expression": "[Total Revenue] - [Total Expense]",
            "formatString": "#,0",
            "lineageTag": "8d8a0d6a-ab9a-4cd4-9396-0fd41237d6f6"
          },
          {
            "name": "MoM NP %",
            "expression": [
              "",
              "VAR PM_np = CALCULATE([Net Profit], DATEADD('Date'[Date], -1, MONTH))",
              "VAR reg_np = [Net Profit]",
              "VAR Diff = reg_np- PM_np",
              "VAR Result = DIVIDE(Diff, PM_np, 0)",
              "RETURN",
              "    Result"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dcc81f7c-39a3-4c5c-9c49-7f693bc0b58a"
          },
          {
            "name": "NP Margin %",
            "expression": "DIVIDE([Net Profit], [PM Revenue], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f576e636-9588-4b13-bf60-8d12914d89a6"
          },
          {
            "name": "Terget Revnue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "17560000/12",
            "lineageTag": "77cf6256-ad85-472c-8ff8-dbeff3069ad9"
          },
          {
            "name": "aa",
            "expression": "CALCULATE([Total Revenue], REMOVEFILTERS('Date'[Month name]))",
            "formatString": "0",
            "lineageTag": "68264d64-17e8-4e1f-837a-e0728925eefa"
          },
          {
            "name": "Terget for Rev",
            "expression": [
              "",
              "VAR unitbusineline = VALUES(Fact_data[Busine_Line])",
              "VAR Result= ",
              "SWITCH (",
              "    unitbusineline,",
              "    \"Sports Equipment\", 6000000, // Replace with your desired target",
              "    \"Sportswear\", 4000000,",
              "    \"Nutrition & Food_Sup\", 2500000,",
              "    0 // Default value if category is not matched",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "formatString": "0",
            "lineageTag": "a8dd6951-6c89-4982-bb86-194e4c68141b"
          },
          {
            "name": "Terget for Exp",
            "expression": [
              "",
              "VAR unitbusineline = VALUES(Fact_data[Busine_Line])",
              "VAR Result= ",
              "SWITCH (",
              "    unitbusineline,",
              "    \"Sports Equipment\", 5000000, // Replace with your desired target",
              "    \"Sportswear\", 3000000,",
              "    \"Nutrition & Food_Sup\", 2500000,",
              "    0 // Default value if category is not matched",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "formatString": "0",
            "lineageTag": "a7f11339-0d58-4b8f-8834-abc8558e8f91"
          },
          {
            "name": "OPEX",
            "expression": "CALCULATE([Total], Fact_data[Revenue / Expense Group]=\"Opex\")",
            "formatString": "#,0",
            "lineageTag": "7ec0f08a-c569-4fb2-8c45-a2ee1c10ae75"
          },
          {
            "name": "EBIT",
            "expression": "[Gross Profit]-[OPEX]",
            "formatString": "#,0",
            "lineageTag": "4d582b38-e0c9-413f-8693-fb256b45f623"
          },
          {
            "name": "EBIT Margin %",
            "expression": "DIVIDE([EBIT], [Total Revenue])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bf233f5b-292f-411c-92af-125d5a1e9d4a"
          },
          {
            "name": "Interest & Tax",
            "expression": "CALCULATE([Total Expense], Fact_data[Revenue / Expense Group] = \"Interest and tax\")",
            "formatString": "#,0",
            "lineageTag": "6e1cecbe-d056-47ef-86e6-4a40aba24a7f"
          },
          {
            "name": "QoQ",
            "displayFolder": "Revnue",
            "expression": [
              "",
              " Var PQ_Rev = CALCULATE([Total Revenue], DATEADD('Date'[Date],-1,QUARTER))",
              " VAR Current_Rev = [Total Revenue]",
              " VAR Result = Current_Rev - PQ_Rev",
              " RETURN",
              " Result",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "704e106c-239c-4b96-8910-36b234a02d47"
          },
          {
            "name": "QoQ%",
            "displayFolder": "Revnue",
            "expression": "DIVIDE([QoQ],[Total Revenue])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "829abba8-7e40-44a4-ab73-8a5222599524"
          },
          {
            "name": "EXP QoQ",
            "expression": [
              "",
              "VAR PQ = CALCULATE([Total Expense], DATEADD('Date'[Date], -1, QUARTER))",
              "VAR Curent = [Total Expense]",
              "VAR Result = Curent - pq",
              "RETURN",
              "Result"
            ],
            "formatString": "#,0",
            "lineageTag": "08a36b91-06da-488b-9c09-4f1b42de97d0"
          },
          {
            "name": "EXP QoQ%",
            "expression": "DIVIDE([EXP QoQ], [Total Expense])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "0908efe4-bed5-4e0b-9629-47a4c6073dba"
          }
        ],
        "partitions": [
          {
            "name": "_Measure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Data Refresh",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7b0d4719-832f-4164-bc08-2be6666d79b2",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e8d196c3-b33a-4361-999f-9f0798341937",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "538c9560-7986-4355-9bcf-205bfd320468",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "39fc7017-0f15-4458-807e-47874a4a229d",
        "partitions": [
          {
            "name": "Data Refresh",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow(),",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"DateTime\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"DateTime\", type datetime}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"DateTime\", \"DateTime - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DateTime - Copy\", \"Date\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Date\", type date}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Changed Type1\", \"DateTime\", \"DateTime - Copy\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column1\",{{\"DateTime - Copy\", \"Time\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"Time\", type time}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e3df2c37451e4eb099dc337c9a2945c1"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "660fa973-7dd9-4187-aff9-34f2ca91224e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Date'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fe0538bb-7515-4ecf-a8d2-a5cce9856280",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date'[Date],\"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "c90f50ae-ba30-4de8-b734-b50a1e190896",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Start_of_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "STARTOFMONTH('Date'[Date])",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "56b8d87a-9c36-4d06-9f27-b181b71b0c9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QTR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "QUARTER('Date'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "60dfacf1-3982-4e3c-ba1e-3df758fafea6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quater",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH('Date'[QTR],",
              "1, \"Q1\",",
              "2, \"Q2\",",
              "3, \"Q3\",",
              "\"Q4\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a91faea9-1194-4814-9339-6a1fea82655c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Short Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date'[Date], \"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "48e501de-1171-48aa-b911-30dc7173b15a",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date'[Date],\"yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "e2f86490-3235-47f9-b2ef-c11d8f302fc6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "QTR Hierarchy",
            "levels": [
              {
                "name": "Quater",
                "column": "Quater",
                "lineageTag": "ccaaf42b-64d7-4562-b702-5a216f89e7d5",
                "ordinal": 0
              },
              {
                "name": "Month Short Name",
                "column": "Month Short Name",
                "lineageTag": "19fa169d-0d78-49ed-889d-a35ad87732c8",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "51821015-e1fc-4e92-ae3e-6ddb2db366d3",
                "ordinal": 2
              }
            ],
            "lineageTag": "368280b5-b0e1-4dec-934c-bb7245376659"
          }
        ],
        "lineageTag": "4209232e-a329-4c24-a7b4-75e622fa3f6e",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(2023,1,1), DATE(2023,12,31))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}